# yaml-language-server: $shema=https://taskfile.dev/schema.json
version: '3'

vars:
  BINARY: '{{if eq OS "windows"}}gradlew.bat{{else}}gradlew{{end}}'
  ENGINE: .engine/{{.BINARY}}

tasks:
  run:
    cmds:
      - docker compose up -d
      - ./{{.ENGINE}} bootRun --configuration-cache

  build:
    cmds:
      - docker compose up -d
      - ./{{.ENGINE}} build --configuration-cache  # TODO: add build docker image

  format:
    cmds:
      - ./{{.ENGINE}} spotlessApply --configuration-cache

  clean:
    cmds:
      - docker compose down
      - ./{{.ENGINE}} clean
      - docker compose up -d

