# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

# 1. SOLUCIÓN DOCKER: Cargamos las variables de entorno para que Docker las reconozca
dotenv: ['.env']

vars:
  # En Windows delegamos en cmd y ejecutamos gradlew.bat en el directorio actual
  GRADLEW: '{{if eq OS "windows"}}cmd /c gradlew.bat{{else}}./gradlew{{end}}'

tasks:
  run:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} bootRun --configuration-cache'

  build:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} build --configuration-cache'  # TODO: add build docker image

  format:
    cmds:
      - '{{.GRADLEW}} spotlessApply --configuration-cache'

  test:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} spotlessCheck --configuration-cache'
      - '{{.GRADLEW}} test --configuration-cache'

  clean:
    cmds:
      - docker compose down
      - '{{.GRADLEW}} clean'
      - docker compose up -d