# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  BINARY: '{{if eq OS "windows"}}gradlew.bat{{else}}gradlew{{end}}'
  ENGINE: .engine/{{.BINARY}}

tasks:
  run:
    cmds:
      - docker compose up -d
      - ./{{.ENGINE}} bootRun

  build:
    cmds:
      - docker compose up -d
      - ./{{.ENGINE}} build # TODO: add build docker image

  format:
    cmds:
      - ./{{.ENGINE}} spotlessApply

  clean:
    cmds:
      - docker compose down
      - ./{{.ENGINE}} clean
      - docker compose up -d

