# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  # Agregamos doble barra \\ en la parte de Windows
  GRADLEW: '{{if eq OS "windows"}}.engine\\gradlew.bat{{else}}./.engine/gradlew{{end}}'

tasks:
  run:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} bootRun --configuration-cache'

  build:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} build --configuration-cache'  # TODO: add build docker image

  format:
    cmds:
      - '{{.GRADLEW}} spotlessApply --configuration-cache'

  test:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} test'

  clean:
    cmds:
      - docker compose down
      - '{{.GRADLEW}} clean'
      - docker compose up -d