# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

dotenv: ['.env']

vars:
  # En Windows delegamos en cmd y ejecutamos gradlew.bat en el directorio actual
  GRADLEW: '{{if eq OS "windows"}}cmd /c gradlew.bat{{else}}./gradlew{{end}}'
  VERSION: '{{.APP_VERSION | default "0.1.0"}}'

tasks:
  run:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} bootRun -PappVersion={{.VERSION}} --configuration-cache'

  build:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} build -PappVersion={{.VERSION}} --configuration-cache'
      - docker build -t spalaxdev/rms-api:{{.VERSION}} .

  format:
    cmds:
      - '{{.GRADLEW}} spotlessApply --configuration-cache'

  test:
    cmds:
      - docker compose up -d
      - '{{.GRADLEW}} spotlessCheck --configuration-cache'
      - '{{.GRADLEW}} test --configuration-cache'

  clean:
    cmds:
      - docker compose down
      - '{{.GRADLEW}} clean'
      - docker compose up -d

  jwtkeys:
    cmds:
      - '{{.GRADLEW}} generate-jwt-keys'
