app:
  env: production
  admin:
    email: ${ADMIN_EMAIL}

spring:
  datasource:

    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 10000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"
      pool-name: RmsHikariPool
      initialization-fail-timeout: -1

logging:
  level:
    root: WARN
    aros.services.rms: WARN
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.zaxxer.hikari: ERROR
    jakarta.persistence: ERROR
    org.flywaydb: ERROR
    aros.services.rms.infraestructure.common.config.RequestLoggingFilter: ERROR
    springframework:
      boot:
        autoconfigure:
          flyway: ERROR

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
