spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 10000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"
      pool-name: RmsHikariPool
      initialization-fail-timeout: -1
