app:
  version: 0.2.9
  env: ${APP_ENV}
  admin:
    email: ${ADMIN_EMAIL:}
    dummy-email: ${DUMMY_EMAIL:}
  jwt:
    issuer: rms-api
    expiration-minutes: 60
    public-key: ${JWT_PUBLIC_KEY:}
    private-key: ${JWT_PRIVATE_KEY:}
  email:
    base-url: ${MAIL_URL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}

spring:
  application:
    name: rms
  profiles:
    active: ${APP_ENV}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true

