logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    aros.services.rms: ${LOG_LEVEL_APP:INFO}
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.zaxxer.hikari: WARN
    jakarta.persistence: WARN
    org.flywaydb: ${LOG_FLYWAY:DEBUG}
    aros.services.rms.infraestructure.common.config.RequestLoggingFilter: ${LOG_REQUEST:DEBUG}
    springframework:
      boot:
        autoconfigure:
          flyway: DEBUG

spring:
  application:
    name: rms
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${DB_ROOT_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 10000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"
      idle-timeout: 300000
      pool-name: RmsHikariPool
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true


springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}

app:
  version: 0.1.0
  env: ${APP_ENV:development}
  admin:
    email: ${ADMIN_EMAIL:}
    dummy-email: ${DUMMY_EMAIL:}
  jwt:
    issuer: rms-api
    expiration-minutes: 60
    public-key: ${JWT_PUBLIC_KEY:}
    private-key: ${JWT_PRIVATE_KEY:}
  email:
    base-url: ${MAIL_URL}
