spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 10000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"
      pool-name: RmsHikariPool
      initialization-fail-timeout: -1
  cloud:
    gcp:
      sql:
        instance-connection-name: ${CLOUD_SQL_INSTANCE}
        database-name: ${DB_NAME}
