/* (C) 2026 */

package aros.services.rms.core.category.domain;

import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Domain model representing an option category for product customization (e.g., "Cooking term",
 * "Milk type"). These define what can be added to or modified in a product.
 *
 * <p>An option category declares its selection mode (how many options can be picked) and, for
 * {@link OptionSelectionType#SINGLE_CHOICE} categories, an optional substitution link to a supply
 * category whose default base-recipe line gets swapped out when a customer picks an option.
 *
 * <p><b>Invariants</b> (enforced fail-fast):
 *
 * <ul>
 *   <li>{@code selectionType} defaults to {@link OptionSelectionType#SINGLE_CHOICE} when null.
 *   <li>{@code replaceSupplyCategoryId} may only be non-null when {@code selectionType ==
 *       SINGLE_CHOICE}. For {@link OptionSelectionType#MULTI_SELECT}, {@link
 *       OptionSelectionType#EXTRA} and {@link OptionSelectionType#REMOVE} the field is forced to
 *       null and assigning a non-null value throws {@link IllegalArgumentException}.
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
public class OptionCategory {
  private Long id;
  private String name;
  private String description;

  /** Selection mode. Defaults to {@link OptionSelectionType#SINGLE_CHOICE} when null. */
  @Builder.Default private OptionSelectionType selectionType = OptionSelectionType.SINGLE_CHOICE;

  /**
   * For SINGLE_CHOICE categories, this references the supply category whose base-recipe line is
   * replaced when a customer picks an option from this category. {@code null} for MULTI_SELECT,
   * EXTRA and REMOVE; setting it otherwise throws.
   */
  private Long replaceSupplyCategoryId;

  /**
   * Validated all-args constructor used by Lombok's {@code @Builder}. Not auto-generated by Lombok
   * (we intentionally omit {@code @AllArgsConstructor}) so the invariant check runs at construction
   * time as well as on setter calls.
   *
   * @param id the option category id
   * @param name the option category name
   * @param description the option category description
   * @param selectionType the selection mode (null → SINGLE_CHOICE)
   * @param replaceSupplyCategoryId the replacement supply category id (nullable; only valid for
   *     SINGLE_CHOICE)
   */
  public OptionCategory(
      Long id,
      String name,
      String description,
      OptionSelectionType selectionType,
      Long replaceSupplyCategoryId) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.selectionType = selectionType == null ? OptionSelectionType.SINGLE_CHOICE : selectionType;
    this.replaceSupplyCategoryId = validateReplacement(this.selectionType, replaceSupplyCategoryId);
  }

  /**
   * Sets the selection type. Clears {@code replaceSupplyCategoryId} if the new mode does not allow
   * a replacement supply category.
   *
   * @param selectionType the new selection type (null → SINGLE_CHOICE)
   */
  public void setSelectionType(OptionSelectionType selectionType) {
    this.selectionType = selectionType == null ? OptionSelectionType.SINGLE_CHOICE : selectionType;
    if (this.selectionType != OptionSelectionType.SINGLE_CHOICE) {
      this.replaceSupplyCategoryId = null;
    }
  }

  /**
   * Sets the replacement supply category id. Only valid when {@code selectionType ==
   * SINGLE_CHOICE}; otherwise throws {@link IllegalArgumentException}.
   *
   * @param replaceSupplyCategoryId the replacement supply category id (nullable)
   */
  public void setReplaceSupplyCategoryId(Long replaceSupplyCategoryId) {
    this.replaceSupplyCategoryId = validateReplacement(this.selectionType, replaceSupplyCategoryId);
  }

  private static Long validateReplacement(OptionSelectionType type, Long replacement) {
    if (type != OptionSelectionType.SINGLE_CHOICE && replacement != null) {
      throw new IllegalArgumentException(
          type + " categories cannot have a replacement supply category (only SINGLE_CHOICE may)");
    }
    return replacement;
  }
}
