/* (C) 2026 */

package aros.services.rms.core.payroll.application.service;

import aros.services.rms.core.common.logger.Logger;
import aros.services.rms.core.common.money.domain.Money;
import aros.services.rms.core.payroll.domain.Payroll;
import aros.services.rms.core.payroll.domain.PayrollStatus;
import aros.services.rms.core.payroll.domain.exception.InvalidPayrollPeriodException;
import aros.services.rms.core.payroll.domain.exception.PayrollAlreadyExistsException;
import aros.services.rms.core.payroll.domain.port.input.RegisterPayrollUseCase;
import aros.services.rms.core.payroll.domain.port.output.PayrollRepositoryPort;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.YearMonth;
import java.util.Currency;
import lombok.RequiredArgsConstructor;

/** Service implementation for registering a new payroll record. */
@RequiredArgsConstructor
public class RegisterPayrollService implements RegisterPayrollUseCase {

  private static final Currency COP = Currency.getInstance("COP");
  private static final BigDecimal EXPECTED_HOURS_THRESHOLD = new BigDecimal("0.8");

  private final PayrollRepositoryPort payrollRepositoryPort;
  private final Logger logger;

  @Override
  public Payroll register(RegisterPayrollCommand cmd) {
    // Validate period
    if (cmd.periodStart() == null || cmd.periodEnd() == null) {
      throw new InvalidPayrollPeriodException("periodStart and periodEnd are required");
    }
    if (cmd.periodEnd().isBefore(cmd.periodStart())) {
      throw new InvalidPayrollPeriodException("periodEnd must not be before periodStart");
    }

    // Check duplicate
    if (payrollRepositoryPort.existsByUserIdAndPeriod(cmd.userId(), cmd.year(), cmd.month())) {
      throw new PayrollAlreadyExistsException(cmd.userId(), cmd.year(), cmd.month());
    }

    // Calculate netAmount = baseSalary + bonuses - deductions
    Money netAmount = cmd.baseSalary().plus(cmd.bonuses()).minus(cmd.deductions());
    if (netAmount.isNegative()) {
      throw new InvalidPayrollPeriodException(
          "netAmount must not be negative (base + bonuses - deductions < 0)");
    }

    // Alert if hours_worked is significantly less than expected (80%)
    // Note: we don't have expectedHours here, but we log a warning if hours is very low
    if (cmd.hoursWorked().compareTo(BigDecimal.ZERO) <= 0) {
      logger.info(
          "Payroll for user {} has hours_worked = {}, will be excluded from cost calculations",
          cmd.userId(),
          cmd.hoursWorked());
    }

    Instant now = Instant.now();
    YearMonth period = YearMonth.of(cmd.year(), cmd.month());
    Payroll payroll =
        new Payroll(
            null, // id generated by DB
            cmd.userId(),
            period,
            cmd.periodStart(),
            cmd.periodEnd(),
            cmd.baseSalary(),
            cmd.bonuses(),
            cmd.deductions(),
            netAmount,
            cmd.hoursWorked(),
            PayrollStatus.PENDING,
            cmd.notes(),
            cmd.performedBy(),
            now,
            now);

    Payroll saved = payrollRepositoryPort.save(payroll);
    logger.info(
        "Registered payroll for user {} period {}-{}, netAmount={}, hours={}",
        cmd.userId(),
        cmd.year(),
        cmd.month(),
        netAmount,
        cmd.hoursWorked());
    return saved;
  }
}
